# output from OpenAI for article "Diana Haecker, 'Council informs Sen. Murkowski of Nome’s needs and wants', Nome Nugget, The (online), 21 Apr 2022 1 for nome...":
[
    {
        "paragraph_id": "Topping the list was...expand water and sewer services.",
        "code": "Economy",
        "quoted_evidence": "Topping the list was funding for the Nome Deep-draft port expansion, but also the city\u2019s ask for funds to further the combined housing project for teachers and Nome police officers, and NJUS projects to enhance the wind farm and expand water and sewer services.",
        "opposition_or_support": "support"
    },
    {
        "paragraph_id": "Part of the housing crisis...by a whopping 900,000 gallons",
        "code": "Sustainability and Climate Issues",
        "quoted_evidence": "to potentially have 40 percent of electrical energy generated by wind, which would decrease reliance on diesel fuel by a whopping 900,000 gallons per year.",
        "opposition_or_support": "support"
    }
]
# output from OpenAI for article "Tyler Rhodes, NSEDC, Communications Director, 'Member communities have five more years to utilize their $1 million for nome...":
[
    {
        "paragraph_id": "Member communities have five...through NSEDC's Community Energy",
        "code": "Economy",
        "quoted_evidence": "NSEDC implemented the Community Energy Fund in 2009 and allocated $1 million to each NSEDC member community for energy-related projects.",
        "opposition_or_support": "support"
    },
    {
        "paragraph_id": "The program aims to reduce...funding for nine different projects.",
        "code": "Sustainability and Climate Issues",
        "quoted_evidence": "The program aims to reduce energy costs for Norton Sound residents by encouraging the construction of renewable energy systems",
        "opposition_or_support": "support"
    },
    {
        "paragraph_id": "NSEDC's Board of Directors...utilize the funding.",
        "code": "Infrastructure",
        "quoted_evidence": "NSEDC's Board of Directors recognizes that it takes time to plan and develop energy infrastructure improvement projects.",
        "opposition_or_support": "support"
    },
    {
        "paragraph_id": "\"The Community Energy Fund...reduce costs for residents.\"",
        "code": "Economy",
        "quoted_evidence": "\"The Community Energy Fund has already made several projects possible that have resulted in safer and more efficient energy systems for many of our communities,\" said NSEDC Board Chairman Dan Harrelson.",
        "opposition_or_support": "support"
    },
    {
        "paragraph_id": "Nome and Unalakleet are...power plant generators.",
        "code": "Sustainability and Climate Issues",
        "quoted_evidence": "Nome and Unalakleet are the only two communities to have fully utilized their available funding, both putting their entire allocation toward large wind energy systems.",
        "opposition_or_support": "support"
    },
    {
        "paragraph_id": "NSEDC encourages municipalities and/or...Community Benefits Director Paul",
        "code": "Sustainability and Climate Issues",
        "quoted_evidence": "NSEDC encourages municipalities and/or utility providers in member communities to explore renewable or energy-efficiency projects that could receive financial support through NSEDC's Community Energy Fund.",
        "opposition_or_support": "support"
    }
]
# output from OpenAI for article "Staff, 'Briefs', Anchorage Daily News (online), 5 Feb 2001 B2 ‹https://infoweb.newsbank.com/apps/news/document-view? for nome...":
[
    {
        "paragraph_id": "Nome Turbine project gets government's...Nome Joint Utility System's demand.",
        "code": "Sustainability and Climate Issues",
        "quoted_evidence": "The turbines would supply less  Joint Utility System's demand.",
        "opposition_or_support": "neutral"
    }
]